name: Nuget Push CI

on:
    release:
        types:
            - published

        # ALLOW MANUAL RUNS
        workflow_dispatch:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: 8.0.x

            - name: Restore dependencies
              run: dotnet restore

            - name: Build
              run: dotnet build --no-restore

            - name: Test
              run: dotnet test --no-build --verbosity normal

            - name: Create the packages
              if: success()
              run: dotnet pack

            - name: Publish Nuget
              if: success()
              run: dotnet nuget push **/Release/*.nupkg --api-key ${{ secrets.NUGET_KEY }} --source https://api.nuget.org/v3/index.json

            - name: Upload asset
              uses: actions/upload-artifact@v3.1.2
              with:
                  path: |
                      **/Release/*.nupkg
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
